### ISSUE TITLE
Can't execute pssi.py, smart card is missing

### ISSUE THREAD

**Issue by nbenm** [Eric-Bourry/pssi#13]
Hi,

I can't execute pssi.py. Here are messages:

```
./pssi.py plugins/emv
Traceback (most recent call last):
  File "./pssi.py", line 28, in <module>
    import card_interface
  File "/divers/fouretout/pssi/pssi/card_interface.py", line 26, in <module>
    from smartcard.util import toHexString
ImportError: No module named smartcard.util
```

Thanks

**Comment by nbenm** [comment]
Must install pyscard.
Done it and everything is ok.
I close the issue.
